### ISSUE TITLE
Master Recording Card Changes: There are inconsistencies in labels, content needing to be exposed etc.

### ISSUE THREAD

**Issue by kenumezaki** [cardstack/dotbc-bugs#12]
Both cosmetic and content changes are suggested in screen shot attached.

<img width="1428" alt="master card" src="https://user-images.githubusercontent.com/26882597/51783134-aee61700-20f2-11e9-81f4-3d08ebd1208c.png">

**Comment by chloedotbc** [comment]
MM:SS fixed - others are not
