### ISSUE TITLE
Bug: User can delete cards thru the UI editing process.  Should not happen.  For Works Writer, you can't seem to add a card with information back

### ISSUE THREAD

**Issue by kenumezaki** [cardstack/dotbc-bugs#17]
I accidentally deleted the Writer card for the work Rose of Cimarron:
https://pouty.pizza/songs/s00009-w000000009-1126102517

It was deleted via the editing interface.  Users should only be able to delete content, not the card itself.

Also, I can't seem to add back the data and card thru the editing interface, as the fields are not permitting input. 

See video here: (sorry Git does not allow video uploads it seems)
https://www.dropbox.com/s/hovq4eanu6hg9fc/Works%20Writer%20Bugs.mov?dl=0

Please reinsert the writer card and info if possible for this work.

**Comment by dnaidionov** [comment]
tracked in cardstack/dotbc#287

**Comment by chloedotbc** [comment]
Today I accidentally deleted the Master Recording card on the matched view of this same song.
