### ISSUE TITLE
DPID: should not be asoociated with artist. 

### ISSUE THREAD

**Issue by kenumezaki** [cardstack/dotbc-bugs#18]
DPIDs for Artists are consitently the same # in artist card.  This ID is not Artist but related to the distributor of the release.  Need to reassociate with the right card (probably release) and move there.  Artist IDs and Type TBD in terms of fix.  To be reviewed by Alex and Greg.  See 2 examples of different artists with same DPID.

<img width="1141" alt="dpid issue" src="https://user-images.githubusercontent.com/26882597/51783958-30dc3d00-20ff-11e9-99f0-23134df1fa1c.png">

<img width="1142" alt="artist" src="https://user-images.githubusercontent.com/26882597/51783968-5f5a1800-20ff-11e9-98d9-44780a33a060.png">

**Comment by dnaidionov** [comment]
tracked in cardstack/dotbc#279

**Comment by dnaidionov** [comment]
fixed

**Comment by chloedotbc** [comment]
It has been removed - but I can't see where it has now gone...? Did we only delete it?

**Comment by dnaidionov** [comment]
Yes. Does it need to be displayed elsewhere?

**Comment by chloedotbc** [comment]
I believe it should be displayed in the Master Owner card since it is a code associated with the organisation (in this case Warner) that owns the master. It is what is known as a "DDEX Party Identifier" and identifies the party who has taken out the DDEX license.

**Comment by dnaidionov** [comment]
Source files didn't contain any data for Master Owners, so that card will be empty for all songs, so currently we don't have anywhere to move that data. When users enter owners they would enter DPIDs then, or if we do another data import with additional Owners data, that should already contain DPIDs
