### ISSUE TITLE
Search on slow connections appears broken (due to lack of loading indicator)

### ISSUE THREAD

**Issue by mitchellshow** [cardstack/dotbc-bugs#2]
Summary
Search on slow connections appears broken

Steps to reproduce
Step 1: Search for anything on a slow connection

Expected result
Search result appears

Actual result
I see a message that says "Please enter terms in the search box" with no indicator the search is happening

Environment
Operating system: Mac
Browser: Chrome

Additional information
We should add a loading indicator while search is executing

**Comment by dnaidionov** [comment]
Tracked in https://github.com/cardstack/dotbc/issues/268
