### ISSUE TITLE
Related to: App Card Appears on Home Screen - the "+" icon at the bottom lets you add data cards even if you're not in a song.

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#22]
Summary

Related to: App Card Appears on Home Screen - the "+" icon at the bottom lets you add data cards even if you're not in a song.

Steps to reproduce

1.  Create new user
2. Log-in
3. Click the "+" icon on the bottom right.

Expected result

It shouldn't be there.

Actual result

It is there and it lets people click a metadata field to begin a card even though you're not in a song - so where is it writing to?

Environment

Operating system: OS X 10.12.6
Browser: Chrome

Additional information
<img width="1425" alt="screen shot 2019-01-26 at 15 14 44" src="https://user-images.githubusercontent.com/46965257/51789089-658ed980-217d-11e9-93b9-2c4fd4e06dc5.png">

Also,  you can't "cancel" - the button doesn't do anything - so I can only click "done editing" which keeps the new app card in a "draft state" - but again, I didn't add any data and it's not associated with a song. 
<img width="1442" alt="screen shot 2019-01-26 at 15 17 06" src="https://user-images.githubusercontent.com/46965257/51789102-94a54b00-217d-11e9-8953-0ecef665f84f.png">

**Comment by dnaidionov** [comment]
tracked in cardstack/dotbc#287
