### ISSUE TITLE
Fields not editable if you click "edit page" icon before you click edit on a card.

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#24]
Summary

If you already have the app card open - and click "edit page" it then makes all fields uneducable.

Steps to reproduce

1. Open works card
2. Click edit page icon first
3. Click the card you want to edit
4. try to edit information - you can't

Expected result

you can edit cards by clicking edit page and then edit item.

Actual result

Fields are locked if you do it in this order.

Environment

Operating system: Mac OS X 10.12.6
Browser: Chrome

Additional information

**Comment by dnaidionov** [comment]
There seems to be a confusion between opening an editor and switching on edit mode. When you click on a pencil icon ![image](https://user-images.githubusercontent.com/1836666/52065310-40ff7c80-2544-11e9-8dec-b4a2d6a2b899.png) it opens editor (right edge), but doesn't enter edit mode - you can tell it by the state of the button in the upper right corner: 
![image](https://user-images.githubusercontent.com/1836666/52065409-75733880-2544-11e9-9023-5a441c084efc.png)
means you are in view mode, and prompts to switch to edit mode

![image](https://user-images.githubusercontent.com/1836666/52065451-8b80f900-2544-11e9-93b8-1509437134fb.png)
means you are in edit mode. When you click "Done Editing" it will return to the view mode. If you just close the card and return to the main song page without explicitly exiting edit mode, you are still in edit mode. That is the reason you are seeing placeholder texts for some fields (referenced in #25)

**Comment by dnaidionov** [comment]
we will improve user experience later, for now it's going to be a matter of training.
