### ISSUE TITLE
Works Writers Card - missing information and fields - possible dummy data still imported

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#28]
See below
<img width="777" alt="screen shot 2019-01-26 at 19 36 13" src="https://user-images.githubusercontent.com/46965257/51791879-e2cc4580-21a1-11e9-951a-f608e7c905ba.png">

**Comment by dnaidionov** [comment]
I did a partial reload of data. all last week's changes have been reverted, but now you have IPI numbers. 

During earlier planning we decided to drop affiliations from the UI. Initial proposed data schema when we was flat, and UI was designed with that in mind. Actual data schema is nested with multiple levels of nesting, and that doesn't fit well with our UI, so we removed some of more complex dependencies - affiliations was one of them.
