### ISSUE TITLE
Artist admin card stays open even when you delete/cancel edits - then search breaks.

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#3]
Summary

Search function not working after "deleting" an artist - but not clicking save, clicking cancel.

Steps to reproduce

1. Search for a song
2. Click artist card - edit button
3. Click "edit page" icon
4. Note: none of the fields were editable - so I clicked "delete"
5. I didn't want to delete so I clicked "cancel"

Expected Result

1. You stay on the song card page and the sidebar goes away
2. Search will still work.

Actual result
1. The main page then goes back to the default.
2. Search function is then broken
3. Artist list card on the sidebar doesn't disappear
What do you actually see happening. E.g.
Title currently says "Wither (acustic version)" (missing o in acoustic)

Environment

Operating system: Mac OS Sierra 10.12.6
Browser:  Chrome

Additional information

<img width="1435" alt="screen shot 2019-01-23 at 19 02 43" src="https://user-images.githubusercontent.com/46965257/51630219-82d76400-1f41-11e9-9cdb-09fb9cf21e34.png">

**Comment by dnaidionov** [comment]
tracked in cardstack/dotbc#269
