### ISSUE TITLE
Publisher & Label Views Can Edit Each Other's Information

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#30]
Summary

When logged in as a publisher - I can edit Master and Release information without sending for approval. 

When logged in as a label - I can edit Works information without sending for approval.

Steps to reproduce

1. Log in as publisher@dotblockchainmedia.com
2. Search for a matched work
3. Edit a master item and save. 

Do the same with label@dotblockchainmedia.com and edit a work card.

Expected result
As a publisher you can SEE the master and recording information but you can't edit it- only request to edit or make an amendment.

Actual result
You can edit it as if you were the owner.

Environment

Operating system: OS 10.12.6
Browser: Chrome

**Comment by dnaidionov** [comment]
This is not a bug, this feature is still being built.
