### ISSUE TITLE
Works designation shows up in a master/release

### ISSUE THREAD

**Issue by kenumezaki** [cardstack/dotbc-bugs#33]
The Works designation shows up on a release/recording object.  Rose of Cimarron is the example.  There may be others.  The Works designation should not show for any recording objects.

<img width="1288" alt="works designation" src="https://user-images.githubusercontent.com/26882597/53020267-c8d5f980-3413-11e9-8d3d-144fe57a4b58.png">

**Comment by dnaidionov** [comment]
This looks like bad data - release shouldn't exist without master. Maybe the master recording details was deleted. In any case, with the release present the name shouldn't me marked as WORKS.

**Comment by kenumezaki** [comment]
How do we get the data back in regarding the master?  I think this may be one where the master object was deleted unintentionally.

**Comment by dnaidionov** [comment]
I already restored it

**Comment by kenumezaki** [comment]
you are the BEST!
