### ISSUE TITLE
Artist should be text box but is dropdown when editing

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#4]
Summary

On editing an artist card - the artist is a dropdown menu not a text box to edit.

Steps to reproduce

1. Search for a song
2. Click artist card - edit button

Expected Result:

1. After clicking "edit page" you can type in a new artist name or edit the artist name as a text box.Y

Actual result

1. There is a dropdown.

Environment

Operating system: Mac OS Sierra 10.12.6
Browser: Chrome

Additional information
<img width="410" alt="screen shot 2019-01-23 at 19 09 44" src="https://user-images.githubusercontent.com/46965257/51636692-c4700b00-1f51-11e9-8aed-3f7c19a1487a.png">

**Comment by dnaidionov** [comment]
tracked in https://github.com/cardstack/dotbc/issues/267
