### ISSUE TITLE
Card Designations: Public or Private

### ISSUE THREAD

**Issue by kenumezaki** [cardstack/dotbc-bugs#9]
Summary: there should be a simple indicator whether a particular card/object is public or private data.  Suggest it is located in lower right of the UI on each card.
<img width="895" alt="public private" src="https://user-images.githubusercontent.com/26882597/51782604-717c8c00-20e8-11e9-89c5-6271a64fc870.png">

**Comment by dnaidionov** [comment]
tracked in cardstack/dotbc#273
